DEFAULT:
    log_level:

LOS_FILE_PATH:
    file_path:

APPLICANT_INPUT:
    start_id:
    VERSION:
    DESCRIPTION:
    FIRST_NAME:
    ADDRESS_FORMAT:
    LAST_NAME:
    DOB:
    HOUSE_NUMBER:
    NO_ITIN:
    APPLYING_ITIN:
    STREET_TYPE:
    STREET_NAME:

COLLATERAL_INPUT:
    start_id :
    VERSION:
    DESCRIPTION:

INFO_INPUT:
    start_id:
    VERSION:
    TESTCASE:
    DEALER_NAME:
    CUSTOMER:
    COAPPLICANT:
    COCUSTOMER:
    PROGRAM:
    UNCOMMON_FEES:
    ADD_CO_APPLICANT:
    ADD_PREVIOUS_ADDRESS:
    BUREAU_TYPE:
    BUSINESS_CO_SIGNER:
    CO_ADD_PREVIOUS_ADDRESS:
    REGISTRATION_STATE:
    PROGRAM_TYPE:
    PRICING_TIER:
    RISK_TIER:
    ASPIRE_LINE5_MAX:
    APPLICATION_TIN_TYPE:

STRUCTURE_INPUT:
    start_id:
    VERSION:
    DESCRIPTION:
    FHF_GAP_CHECK:
    LIFE_INSURANCE:
    OFFERED_WARRANTY:
    FREIGHT_FEE:
